### ISSUE TITLE
gnarwl exits with RC=1 on LDAP failures

### ISSUE THREAD

**Issue by bernhardschmidt** [fln/gnarwl#8]
Filing here so I don't forget, I'll look at it as soon as I can in case noone beats me to it.

We just had an issue with gnarwl bouncing mails when the LDAP server was down. In https://github.com/fln/gnarwl/blob/master/src/dbaccess.c every LDAP error results in `exit(EXIT_FAILURE)`. At least some of them should probably be changed into `exit(EX_TEMPFAIL)`. You probably need to pull in /usr/include/sysexits.h for this.

**Comment by fln** [comment]
I think this would be a good improvement. Did you tested it? Does your MTA retries executing gnarwl if it exists with EX_TEMPFAIL?

**Comment by bernhardschmidt** [comment]
Sort of, I have tested that gnarwl exits with RC=75 when the LDAP server is unavailable (only did the basic test with listing an unreachable server though, but I think it should work for any LDAP errors) and I know that postfix retries on EX_TEMPFAIL.
